version : "3"
services :
   csv_server :
        image: 'infracloudio/csvserver:latest'
        volumes :
           - "/root/inputFile.csv:/csvserver/inputdata"
        ports:
           - "9393:9300"
        environment:
           - "CSVSERVER_BORDER=Orange"